version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql-engine:
    ports:
    - "8080:8080"
    image: hasura/graphql-engine:v1.2.0-beta.3
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set "false" to disable console
      HASURA_GRAPHQL_ADMIN_SECRET: ${ADMIN_SECRET} 
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
  # caddy:
  #   image: abiosoft/caddy:1.0.3-no-stats
  #   depends_on:
  #   - "graphql-engine"
  #   command:
  #   - -agree
  #   - -conf
  #   - /etc/Caddyfile
  #   restart: always
  #   ports:
  #   - "80:80"
  #   - "443:443"
  #   volumes:
  #   - ./Caddyfile:/etc/Caddyfile
  #   - caddy_certs:/root/.caddy
volumes:
  db_data:
  caddy_certs:
